name: CI de sitio Jekyll

on:
  push:
    branches: [ "Principal" ]
  pull_request:
    branches: [ "Principal" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar cach√© de Bundler
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Construir el sitio en contenedor Jekyll
        run: |
          docker run \
            -v ${{ github.workspace }}:/srv/jekyll \
            -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
            jekyll/builder:latest /bin/bash -c \
            "chmod -R 755 /srv/jekyll && jekyll build --future"

      - name: Validar enlaces internos
        run: |
          docker run \
            -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
            jekyll/builder:latest /bin/bash -c \
            "bundle exec htmlproofer /srv/jekyll/_site --disable-external"

      - name: Subir artefacto del sitio
        uses: actions/upload-artifact@v4
        with:
          name: Sitio-Jekyll
          path: _site
